# -*- coding: utf-8 -*-
"""DS 18-3-26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KX6ChiYDyeO86NFHmIFlnQU69kLifTGj
"""

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, ax in enumerate(axes):
    x = np.linspace(0, 10, 100)
    y = np.sin(x + i)
    ax.plot(x, y)
    ax.set_title(f'Subplot {i+1}')
    ax.set_xlabel('X-axis')
    ax.set_ylabel('Y-axis')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

categories = ['A', 'B', 'C', 'D', 'E']
values = [23, 45, 56, 12, 39]

plt.figure(figsize=(8, 5))
plt.bar(categories, values, color='skyblue')

plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Bar Chart')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i in range(5):
    ax = axes[i]
    x = np.linspace(0, 10, 100)
    y = np.sin(x + i * 0.5)
    ax.plot(x, y)
    ax.set_title(f'Subplot {i+1}')
    ax.set_xlabel('X-axis')
    ax.set_ylabel('Y-axis')

if len(axes) > 5:
    fig.delaxes(axes[5])

plt.tight_layout()
plt.show()